site_name: Next-gen Kaldi

repo_url: https://github.com/k2-fsa

theme:
  name: material
  custom_dir: custom
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
    - Support: browser-support.md
    - Site: creating-your-site.md
    - Custom: customization.md
  - Docs:
    - k2: https://k2-fsa.github.io/k2/
    - icefall: https://k2-fsa.github.io/k2/
    - lhotse: https://k2-fsa.github.io/k2/

