# Project information
site_name: Next-gen Kaldi
site_url: https://k2-fsa.org
site_author: Next-gen Kaldi team
site_description: >-
  Next-gen Kaldi

# Repository
repo_name: https://github.com/k2-fsa
repo_url: https://github.com/k2-fsa

# Copyright
copyright: Copyright &copy; 2019 - 2023 Next-gen Kaldi team

theme:
  name: material
  custom_dir: custom
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    scheme: k2

  font:
    text: Roboto
    code: Roboto Mono

  favicon: assets/k2.png
  logo: assets/k2.png

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Installation:
    - k2: installation/k2.md
    - icefall: installation/icefall.md
    - lhotse: installation/lhotse.md
    - sherpa: installation/sherpa.md
    - sherpa-ncnn: installation/sherpa-ncnn.md
    - sherpa-onnx: installation/sherpa-onnx.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Train a model: tutorials/train.md
    - Deploy: tutorials/deploy.md
    - Build an Android demo: tutorials/android.md
  - Docs:
    - k2: docs/k2.md
    - lhotse: docs/lhotse.md
    - icefall: docs/icefall.md
    - sherpa: docs/sherpa.md
    - sherpa-ncnn: docs/sherpa-ncnn.md
    - sherpa-onnx: docs/sherpa-onnx.mc
  - Demo: demo.md
  - Models: models.md
  


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
