authors:
  pkufool:
    name: pkufool
    description: Xiaomi AI Lab
    avatar: https://avatars.githubusercontent.com/u/11765074?v=4
    url: https://pkufool.github.io/
  yaozengwei:
    name: yaozengwei
    description: Xiaomi AI Lab
    avatar: https://avatars.githubusercontent.com/u/19564185?v=4
    url: https://scholar.google.com/citations?user=f3Eo9S0AAAAJ&hl=zh-CN