name: Deploy site
on:
  push:
    branches:
      - main_page
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install requirements
      shell: bash
      run: |
        python3 -m pip install -r requirements.txt

    - name: Build pages
      shell: bash
      run: |
        mkdocs build -f mkdocs.yml
        mkdocs build -f mkdocs-zh-CN.yml

    - name: Deploy pages
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: site
        target: /home/kingway/code/nextgenkaldi